// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	auth "antonio/features/authentication"

	mock "github.com/stretchr/testify/mock"

	users "antonio/features/users"
)

// Business is an autogenerated mock type for the Business type
type Business struct {
	mock.Mock
}

// Login provides a mock function with given fields: data
func (_m *Business) Login(data users.Core) (auth.Core, error) {
	ret := _m.Called(data)

	var r0 auth.Core
	if rf, ok := ret.Get(0).(func(users.Core) auth.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(auth.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
