// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	users "antonio/features/users"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// TokenAuthentication provides a mock function with given fields: data
func (_m *Data) TokenAuthentication(data users.Core) (users.Core, error) {
	ret := _m.Called(data)

	var r0 users.Core
	if rf, ok := ret.Get(0).(func(users.Core) users.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(users.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
